"""+user_id

Revision ID: 1c2f2a87f1db
Revises: 1f725cba805f
Create Date: 2021-09-03 11:20:51.402415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2f2a87f1db'
down_revision = '1f725cba805f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'user_id')
    # ### end Alembic commands ###
