"""uuid to article

Revision ID: 832888d7a6ad
Revises: 1c2f2a87f1db
Create Date: 2021-09-06 15:02:20.503517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832888d7a6ad'
down_revision = '1c2f2a87f1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('uuid', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'uuid')
    # ### end Alembic commands ###
